server:
  port: 8095

spring:
  application:
    name: podicom
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: llama3.2
          temperature: 0.7
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
            pgvector:
              initialize-schema: true
              dimensions: 768
              index-type: hnsw

  datasource:
    url: jdbc:postgresql://localhost:5432/gapgoft
    username: gapgoft
    password: gapgoft
    driver-class-name: org.postgresql.Driver

