server:
  port: 8095
spring:
  ai:
    ollama:
      chat:
        options:
          model: llama3.1
          num-ctx: 4096
      embedding:
        options:
          model: nomic-embed-text
  datasource:
    url: jdbc:postgresql://localhost:5432/gapgoft
    username: gapgoft
    password: gapgoft
    driver-class-name: org.postgresql.Driver


  vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        index-type: hnsw