server:
  port: 8090
spring:
  ai:
    ollama:
      chat:
        options:
          model: llama3.1
          num-ctx: 4096
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        index-type: hnsw
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
