server:
  port: 8090

spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7

  datasource:
    url: jdbc:postgresql://localhost:5432/xxxx
    username: xxx
    password: xxx
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # JWT Secret and Expiration settings
  security:
    jwt:
      secret: your_secret_key
      expiration: 3600000 # 1 hour in milliseconds

  vectorstore:
   pgvector:
     initialize-schema: true
     dimensions: 768
     index-type: hnsw
