server:
  port: 8090
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
#    vectorstore:
#      pgvector:
#        initialize-schema: true
#        dimensions: 768
#        index-type: hnsw